### ISSUE TITLE
WARNING: cidr4.txt includes "127.0.0.0/24" entry!!! 

### ISSUE THREAD

**Issue by M-Stenzel** [touhidurrr/iplist-youtube#15]
Hi,
yesterday I downloaded the CIDR address range, and appliead it by means of crowdsec.
BUT... this list includes **127.0.0.0/24**!!!

I did not check this list beforehand, but ended up with a compromised server, obviously if it cannot reach the localhost...

Just a kind remark to remove the entry in order to not let anyone dive into troubles...

**Comment by touhidurrr** [comment]
![image](https://github.com/user-attachments/assets/adb4faf7-cb74-4daa-9e21-90c821007849)

Not sure how this even got into the list, sigh...

**Comment by touhidurrr** [comment]
fixed with aeef61257ddb07b25f00697f707adb7aef8ebe98, thanks for reporting!
