### ISSUE TITLE
IPv4 range list

### ISSUE THREAD

**Issue by realgooseman** [touhidurrr/iplist-youtube#6]
Hi @touhidurrr,

Thanks for this repo,
I needed the IP's linked to YouTube to whitelist them on my VPN and bypass load captchas.

Possible to add a list of YouTube's IPv4 addresses but in ranges with CIDR ?
The list would be shorter and easier to enter and manage for whitelists/blocklists.

There's [this link](https://www.gstatic.com/ipranges/goog.json) which provides all IPv4 addresses linked to Google with ranges but it's too broad and includes everything.

**Comment by touhidurrr** [comment]
Thanks for appreciating the project. I once thought something along these lines, given that x.x.x.A and x.x.x.B belongs to a big tech company, all the ips between x.x.x.A and x.x.x.B also belongs to the same company. This should be considerably reliable given that ips are bought and sold on blocks.
Do you think writing a script that uses this logic to build a merged ranges list would work? Kindly let me know your thoughts about it.

**Comment by realgooseman** [comment]
I'm not too experienced, but I've seen tools online that let you enter starting and ending IP's to give you CIDR ranges like [here](https://www.meridianoutpost.com/resources/etools/network/convert-ip-to-CIDR.php).

Actually, a lot of the IP's listed on your IPv4 script are already ranged in the Google's official IPv4 list I showed before [here](https://www.gstatic.com/ipranges/goog.json).
I'm not sure how it can be implemented, but it would help in creating a compact IPv4 range list for YouTube only.

**Comment by touhidurrr** [comment]
@realgooseman I added test support for CIDR,
https://github.com/touhidurrr/iplist-youtube/commit/0b2a93f4274f26a0e0fe9afee5b8d525bc0d922a
https://github.com/touhidurrr/iplist-youtube/blob/main/cidr4.txt

This versions code is messed up and I will clean up later. However the CIDR list should work fine. If you you want a shorter CIDR file, you might want to change the value `maskLastNBits` in https://github.com/touhidurrr/iplist-youtube/blob/0b2a93f4274f26a0e0fe9afee5b8d525bc0d922a/cidr.py#L24 to a larger number and try to generate a list yourself.

That's all for now, hope that helps.

**Comment by realgooseman** [comment]
Amazing, thanks for your work. I'm sure it will be useful for people who come across your repo (like I did).

**Comment by touhidurrr** [comment]
Resolved with https://github.com/touhidurrr/iplist-youtube/commit/b5319b3aa85961a5fc83945de806a227cede0e46. See [cidr4.txt](https://raw.githubusercontent.com/touhidurrr/iplist-youtube/main/cidr4.txt) and [cidr6.txt](https://raw.githubusercontent.com/touhidurrr/iplist-youtube/main/cidr6.txt).
