### ISSUE TITLE
Obtaining the IP of youtube needs to be optimized

### ISSUE THREAD

**Issue by cnhap** [touhidurrr/iplist-youtube#8]
The IP was discovered in the past two days.
`
1.225.35.175:443
142.251.90.135:443
142.251.90.136:443
172.217.137.138:443
173.194.49.7:443
173.194.49.71:443
173.194.51.70:443
209.85.228.137:443
209.85.228.231:443
209.85.229.73:443
211.49.146.15:443
74.125.102.136:443
74.125.102.138:443
74.125.164.8:443
`

**Comment by touhidurrr** [comment]
Can you explain the issue a little more? For example what do we need to optimize and what is the list of ips you provided do?

**Comment by cnhap** [comment]
~我不懂英文，我之前是用谷歌翻译的~
我只是想反馈youtube的ip列表不全，提供的就是不在列表里的IP，可实际上是我盒子播放youtube实际使用的ip。
您能看懂就看吧，看不懂就请忽略吧。

**Comment by touhidurrr** [comment]
Result using IP Lookup tools:
| IP | ASN | Organization |
|:--:|:--:|:--:|
| 173.194.49.7 | AS15169 | Google LLC |
| 211.49.146.15 | AS9318 | SK Broadband Co Ltd |
| 74.125.102.138 | AS15169 | Google LLC |
| 142.251.90.136 | AS15169 | Google LLC |
| 209.85.228.231 | AS15169 | Google LLC |
| 74.125.102.136 | AS15169 | Google LLC |
| 173.194.49.71 | AS15169 | Google LLC |
| 173.194.51.70 | AS15169 | Google LLC |
| 209.85.228.137 | AS15169 | Google LLC |
| 209.85.229.73 | AS15169 | Google LLC |
| 172.217.137.138 | AS15169 | Google LLC |
| 1.225.35.175 | AS9318 | SK Broadband Co Ltd |
| 74.125.164.8 | AS15169 | Google LLC |
| 142.251.90.135 | AS15169 | Google LLC |
Although I do not know how to verify if these ips are used by YouTube.

**Comment by touhidurrr** [comment]
After some deliberation, I decided to add the IPs for which a match exist at `/8` (#9).
Added IPs:
- 173.194.49.7
- 74.125.102.138
- 74.125.102.136
- 173.194.49.71
- 173.194.51.70
- 74.125.164.8

Ignored IPs:
- 142.251.90.136
- 209.85.228.231
- 209.85.228.137
- 209.85.229.73
- 172.217.137.138
- 142.251.90.135

Won't be added:
- 211.49.146.15
- 1.225.35.175
